services:
  db:
    image: ankane/pgvector:latest
    container_name: postgres-pgvector
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  embeddings-api:
    build: ./embeddings-api
    ports:
      - '8000:8000'
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: local
      DB_USER: postgres
      DB_PASSWORD: 123
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
