name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Setup environment
        run: |
          cp .env.example .env
          echo "DATABASE_URL=postgresql://postgres:123@localhost:5432/test" >> .env
          echo "AUTH_SECRET=test-secret-key-for-ci" >> .env
          echo "AUTH_TRUST_HOST=true" >> .env

      - name: Run database migrations
        run: pnpm db:push
        env:
          DATABASE_URL: postgresql://postgres:123@localhost:5432/test

      - name: Run tests
        run: pnpm test
        env:
          DATABASE_URL: postgresql://postgres:123@localhost:5432/test

      - name: Build project
        run: pnpm build
        env:
          DATABASE_URL: postgresql://postgres:123@localhost:5432/test

      - name: Run linting
        run: pnpm lint

      - name: Run type checking
        run: pnpm check
